# Generated by Django 4.0 on 2025-01-12 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Lotto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numbers', models.CharField(max_length=100)),
                ('is_auto', models.BooleanField(default=True)),
                ('winning_numbers', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
    ]
